/*Timeless Tales is a retro text adventure created and published by Felix T. Vogel in 2023*/

export const startingItems = [
    {
        name: "Wooden Club",
        slot: "Weapon",
        attack: 1,
        value: 10,
        weight: 5,
    },
    {
        name: "Mother's Carrot Cake",
        slot: "Consumable",
        rarity: "famous",
        value: 40,
        weight: 0.5,
    },
    {
        name: "Father's Zucchini Cake",
        slot: "Consumable",
        rarity: "famous",
        value: 40,
        weight: 0.5,
    },
];

export const startingEquipment = {
    Armor: {
        name: "Linen Shirt",
        slot: "Armor",
        attack: 0,
        defense: 1,
        value: 1,
        weight: 1,
    },
    Underwear: {
        name: "Cozy Underpants",
        slot: "Underwear",
        attack: 0,
        defense: 0,
        value: 20,
        weight: 0.5,
    },
    Pants: {
        name: "Linen Pants",
        slot: "Pants",
        attack: 0,
        defense: 1,
        value: 2,
        weight: 1,
    },
    Socks: {
        name: "Worn Socks",
        slot: "Socks",
        attack: 0,
        defense: 1,
        value: 1,
        weight: 0.5,
    },
    Boots: {
        name: "Lousy Sandals",
        slot: "Boots",
        attack: 0,
        defense: 1,
        value: 3,
        weight: 1.5,
    },
};

export const locations = [
    { name: "a dark forest", worthMultiplier: 0, itemChance: 40, enemyChance: 50 },
    { name: "an abandoned castle", worthMultiplier: 0, itemChance: 90, enemyChance: 70 },
    { name: "a mysterious cave", worthMultiplier: 0, itemChance: 70, enemyChance: 80 },
    { name: "a small village", worthMultiplier: 2, maxItemCount: 3, itemChance: 20, enemyChance: 5 },
    { name: "a treacherous mountain path", worthMultiplier: 0, itemChance: 30, enemyChance: 40 },
    { name: "a town with a buzzing haven", worthMultiplier: 0.4, maxItemCount: 10, itemChance: 20, enemyChance: 0 },
    { name: "a peaceful riverside settlement", worthMultiplier: 1.5, maxItemCount: 5, itemChance: 25, enemyChance: 0 },
    { name: "a bustling city", worthMultiplier: 0.2, maxItemCount: 20, itemChance: 10, enemyChance: 0 },
    { name: "a hidden elven village", worthMultiplier: 2, maxItemCount: 4, itemChance: 30, enemyChance: 0 },
    { name: "a tranquil mountain monastery", worthMultiplier: 3, maxItemCount: 2, itemChance: 40, enemyChance: 30 },
    { name: "a coastal fishing town", worthMultiplier: 1, maxItemCount: 7, itemChance: 15, enemyChance: 20 },
    { name: "an ancient dwarven stronghold", worthMultiplier: 1, maxItemCount: 6, itemChance: 20, enemyChance: 10 },
    { name: "a mystical forest glade", worthMultiplier: 0, maxItemCount: 0, itemChance: 90, enemyChance: 80 },
    { name: "a haunted graveyard", worthMultiplier: 0, itemChance: 80, enemyChance: 90 },
    { name: "a cursed swamp", worthMultiplier: 0, itemChance: 60, enemyChance: 70 },
    { name: "an arcane library", worthMultiplier: 5, maxItemCount: 1, itemChance: 95, enemyChance: 10 },
    { name: "a fiery volcanic lair", worthMultiplier: 0, itemChance: 50, enemyChance: 80 },
    { name: "a magical floating island", worthMultiplier: 0, maxItemCount: 0, itemChance: 60, enemyChance: 20 },
    { name: "an underwater city", worthMultiplier: 2, maxItemCount: 5, itemChance: 30, enemyChance: 0 },
    { name: "a quiet forest grove", worthMultiplier: 0, maxItemCount: 4, itemChance: 35, enemyChance: 30 },
    { name: "a desert oasis", worthMultiplier: 3, maxItemCount: 2, itemChance: 45, enemyChance: 40 },
    { name: "a frosty tundra", worthMultiplier: 0, itemChance: 20, enemyChance: 40 },
    { name: "a bustling market square", worthMultiplier: 0.5, maxItemCount: 15, itemChance: 10, enemyChance: 10 },
    { name: "a windswept plateau", worthMultiplier: 0, itemChance: 30, enemyChance: 30 },
    { name: "a misty valley", worthMultiplier: 0, itemChance: 20, enemyChance: 40 },
    { name: "an enchanted fairy glen", worthMultiplier: 4, maxItemCount: 1, itemChance: 55, enemyChance: 5 },
    { name: "a mystical waterfall", worthMultiplier: 0, maxItemCount: 0, itemChance: 90, enemyChance: 5 },
    { name: "a magical academy", worthMultiplier: 5, maxItemCount: 1, itemChance: 10, enemyChance: 5 },
    { name: "a dense jungle", worthMultiplier: 0, itemChance: 25, enemyChance: 45 },
    { name: "a quiet monastery", worthMultiplier: 3, maxItemCount: 3, itemChance: 25, enemyChance: 20 },
    { name: "a towering castle", worthMultiplier: 1, maxItemCount: 7, itemChance: 20, enemyChance: 30 },
    { name: "a serene lakeside village", worthMultiplier: 1.5, maxItemCount: 5, itemChance: 25, enemyChance: 10 },
    { name: "a forgotten ancient city", worthMultiplier: 0, itemChance: 75, enemyChance: 70 },
    { name: "a lively tavern", worthMultiplier: 1, maxItemCount: 6, itemChance: 15, enemyChance: 30 },
    { name: "a crumbling fortress", worthMultiplier: 0, itemChance: 65, enemyChance: 60 },
    { name: "a beautiful palace", worthMultiplier: 2, maxItemCount: 4, itemChance: 20, enemyChance: 10 },
    { name: "a secluded mountain village", worthMultiplier: 1.5, maxItemCount: 4, itemChance: 30, enemyChance: 50 },
    { name: "the company of a desert caravan", worthMultiplier: 1, maxItemCount: 6, itemChance: 15, enemyChance: 40 },
    { name: "a dangerous forest", worthMultiplier: 0, itemChance: 35, enemyChance: 90 },
    { name: "a lively festival", worthMultiplier: 0.1, maxItemCount: 12, itemChance: 40, enemyChance: 20 },
    { name: "a ruined temple", worthMultiplier: 0, itemChance: 70, enemyChance: 60 },
    { name: "a mystical grove", worthMultiplier: 0, maxItemCount: 0, itemChance: 40, enemyChance: 30 },
    { name: "a treacherous canyon", worthMultiplier: 0, itemChance: 20, enemyChance: 75 },
    { name: "a sprawling desert", worthMultiplier: 0, itemChance: 10, enemyChance: 20 },
    { name: "a lush valley", worthMultiplier: 0, maxItemCount: 0, itemChance: 25, enemyChance: 30 },
    { name: "a sunlit meadow", worthMultiplier: 0, maxItemCount: 0, itemChance: 20, enemyChance: 20 },
    { name: "a gloomy marshland", worthMultiplier: 0, itemChance: 50, enemyChance: 50 },
    { name: "a hidden grotto", worthMultiplier: 0, maxItemCount: 0, itemChance: 65, enemyChance: 20 },
    { name: "a snowy mountain peak", worthMultiplier: 0, itemChance: 30, enemyChance: 30 },
    { name: "a pirate cove", worthMultiplier: 0, itemChance: 80, enemyChance: 80 },
    { name: "a prosperous farmstead", worthMultiplier: 1.5, maxItemCount: 5, itemChance: 20, enemyChance: 30 },
    { name: "a quaint cottage", worthMultiplier: 0.5, maxItemCount: 3, itemChance: 25, enemyChance: 40 },
    { name: "a fortified outpost", worthMultiplier: 1, maxItemCount: 6, itemChance: 15, enemyChance: 20 },
    { name: "a lively street fair", worthMultiplier: 0.7, maxItemCount: 12, itemChance: 10, enemyChance: 15 },
    { name: "an isolated hermit's hut", worthMultiplier: 3, maxItemCount: 1, itemChance: 40, enemyChance: 20 },
    { name: "a sprawling vineyard", worthMultiplier: 0.8, maxItemCount: 5, itemChance: 20, enemyChance: 50 },
    { name: "a charming inn", worthMultiplier: 1, maxItemCount: 6, itemChance: 15, enemyChance: 10 },
    { name: "a windswept moor", worthMultiplier: 0, itemChance: 20, enemyChance: 45 },
    { name: "an abandoned mine", worthMultiplier: 0, itemChance: 60, enemyChance: 50 },
    { name: "a nomad encampment", worthMultiplier: 1, maxItemCount: 6, itemChance: 15, enemyChance: 30 },
    { name: "a tranquil garden", worthMultiplier: 2, maxItemCount: 3, itemChance: 30, enemyChance: 10 },
    { name: "a bustling port", worthMultiplier: 0.6, maxItemCount: 10, itemChance: 10, enemyChance: 10 },
    { name: "a secret hideout", worthMultiplier: 2, maxItemCount: 4, itemChance: 25, enemyChance: 20 },
    { name: "a vibrant marketplace", worthMultiplier: 0.5, maxItemCount: 30, itemChance: 10, enemyChance: 15 },
    { name: "a forgotten catacomb", worthMultiplier: 0, itemChance: 75, enemyChance: 65 },
    { name: "a floating cloud city", worthMultiplier: 2, maxItemCount: 5, itemChance: 30, enemyChance: 1 },
    { name: "a dense bamboo forest", worthMultiplier: 0, itemChance: 25, enemyChance: 35 },
    { name: "a magical menagerie", worthMultiplier: 3, maxItemCount: 2, itemChance: 45, enemyChance: 60 },
    { name: "a grand library", worthMultiplier: 4, maxItemCount: 1, itemChance: 25, enemyChance: 10 },
    { name: "a church sitting in a mountain range", worthMultiplier: 6, maxItemCount: 4, itemChance: 0, enemyChance: 20 },
    { name: "an eerie ghost town", worthMultiplier: 0, itemChance: 40, enemyChance: 40 },
];

export const weathers = [
    "sunny",
    "rainy",
    "foggy",
    "clear",
    "clouded",
    "hot",
    "frosty",
];

function getRandomItem(items) {
    const randomIndex = Math.floor(Math.random() * items.length);
    return items[randomIndex];
}

const dragonlordDrops = [
    { name: "Dragonlord's Tooth", slot: "Amulet", attack: 5, defense: 5, rarity: "legendary", weight: 1, value: 1000, class: "Warrior" },
    { name: "Dragonbone", slot: "Weapon", attack: 24, rarity: "legendary", weight: 50, value: 1000, class: "Warrior" },
    { name: "Dragonscale Leggings", slot: "Pants", defense: 10, attack: 0, rarity: "legendary", weight: 11, value: 1000, class: "none" },
    { name: "Dragonlord's Claw", slot: "Gloves", attack: 4, defense: 4, rarity: "legendary", weight: 3, value: 1000, class: "Warrior" },
    { name: "Dragonlord's Heart", slot: "Accessory", attack: 3, defense: 5, rarity: "legendary", weight: 1, value: 1000, class: "Wizard" },
    { name: "Dragonlord's Scalemail", slot: "Armor", attack: 2, defense: 12, rarity: "legendary", weight: 15, value: 1000, class: "none" },
    { name: "Dragonlord's Greaves", slot: "Boots", attack: 2, defense: 6, rarity: "legendary", weight: 5, value: 1000, class: "none" },
];

const kingOfLightDrops = [
    { name: "Crown of Light", slot: "Helmet", attack: 0, defense: 10, rarity: "legendary", weight: 5, value: 1000 },
    { name: "Wand of Light", slot: "Weapon", attack: 20, defense: 2, rarity: "legendary", weight: 2, value: 1000, class: "Wizard" },
    { name: "Ring of Light", slot: "Accessory", attack: 3, defense: 5, rarity: "legendary", weight: 1, value: 1000, class: "Wizard" },
    { name: "Gloves of Light", slot: "Gloves", attack: 0, defense: 8, rarity: "legendary", weight: 3, value: 1000, class: "none" },
    { name: "Lightbringer's Cloak", slot: "Armor", attack: 1, defense: 11, rarity: "legendary", weight: 8, value: 1000, class: "Rogue" },
    { name: "Lightbringer's Everlasting Salve", slot: "Socks", attack: 0, defense: 3, rarity: "legendary", weight: 1, value: 1000, class: "Rogue" },
    { name: "Invisible Boots", slot: "Boots", attack: 0, defense: 4, rarity: "legendary", weight: 4, value: 2000, class: "none" },
];

const warlordDrops = [
    { name: "Warlord's Sword", slot: "Weapon", attack: 25, defense: -4, rarity: "legendary", weight: 15, value: 1000, class: "Warrior" },
    { name: "Warlord's Shield", slot: "Shield", attack: 0, defense: 15, rarity: "legendary", weight: 10, value: 1000, class: "Knight" },
    { name: "Warlord's Gauntlets", slot: "Gloves", attack: 3, defense: 5, rarity: "legendary", weight: 5, value: 1000, class: "none" },
    { name: "Warlord's Plate", slot: "Armor", attack: 0, defense: 13, rarity: "legendary", weight: 20, value: 1000, class: "Knight" },
    { name: "Warlord's Boots", slot: "Boots", attack: 2, defense: 5, rarity: "legendary", weight: 6, value: 1000, class: "Warrior" },
    { name: "Warlord's Helm", slot: "Helmet", attack: 1, defense: 10, rarity: "legendary", weight: 8, value: 1000, class: "Knight" },
    { name: "Warlord's Cape", slot: "Cloak", attack: 0, defense: 7, rarity: "legendary", weight: 4, value: 1200, class: "Archer" },
];

const queenOfEmberDrops = [
    { name: "Crown of Ember", slot: "Helmet", attack: 5, defense: 2, rarity: "legendary", weight: 5, value: 1000, class: "Rogue" },
    { name: "Staff of Ember", slot: "Weapon", attack: 20, defense: 5, rarity: "legendary", weight: 15, value: 1000, class: "Wizard" },
    { name: "Burning Mace", slot: "Weapon", attack: 24, defense: -10, rarity: "legendary", weight: 0.5, value: 1000, class: "Warrior" },
    { name: "Ember Boots", slot: "Boots", attack: 4, defense: 4, rarity: "legendary", weight: 4, value: 1000, class: "Archer" },
    { name: "Ember Necklace", slot: "Accessory", attack: 5, defense: 2, rarity: "legendary", weight: 1, value: 1000, class: "none" },
    { name: "Ember Robe", slot: "Armor", attack: 2, defense: 10, rarity: "legendary", weight: 6, value: 1000, class: "Rogue" },
    { name: "Burning Socks of Pain", slot: "Socks", attack: 15, defense: -10, rarity: "legendary", weight: 1, value: 1000, class: "none" },
];

const titanDrops = [
    { name: "Titan's Helmet", slot: "Helmet", attack: 3, defense: 8, rarity: "legendary", weight: 8, value: 1000, class: "none" },
    { name: "Titan's Hammer", slot: "Weapon", attack: 28, defense: 2, rarity: "legendary", weight: 18, value: 1000, class: "Warrior" },
    { name: "Titan's Belt", slot: "Belt", attack: 4, defense: 6, rarity: "legendary", weight: 2, value: 1000, class: "none" },
    { name: "Titan's Bracers", slot: "Gloves", attack: 2, defense: 7, rarity: "legendary", weight: 6, value: 1000, class: "Warrior" },
    { name: "Titan's Plate", slot: "Armor", attack: 1, defense: 14, rarity: "legendary", weight: 25, value: 1000, class: "Knight" },
    { name: "Titan's Greaves", slot: "Boots", attack: 3, defense: 7, rarity: "legendary", weight: 9, value: 1000, class: "none" },
    { name: "Titan's Chainmail Socks", slot: "Socks", attack: 0, defense: 4, rarity: "legendary", weight: 2, value: 1000, class: "none" },
];

const swiftAssassinDrops = [
    { name: "Assassin's Hood", slot: "Helmet", attack: 6, defense: 3, rarity: "legendary", weight: 3, value: 1100, class: "Rogue" },
    { name: "Assassin's Dagger", slot: "Weapon", attack: 30, defense: -2, rarity: "legendary", weight: 4, value: 1100, class: "Rogue" },
    { name: "Assassin's Amulet", slot: "Accessory", attack: 7, defense: 2, rarity: "legendary", weight: 1, value: 1100, class: "none" },
    { name: "Assassin's Gloves", slot: "Gloves", attack: 5, defense: 3, rarity: "legendary", weight: 2, value: 1100, class: "Archer" },
    { name: "Assassin's Leather Armor", slot: "Armor", attack: 4, defense: 7, rarity: "legendary", weight: 10, value: 1100, class: "none" },
    { name: "Assassin's Boots", slot: "Boots", attack: 5, defense: 4, rarity: "legendary", weight: 5, value: 1100, class: "Archer" },
    { name: "Assassin's Socks", slot: "Socks", attack: 3, defense: 1, rarity: "legendary", weight: 0.5, value: 1100, class: "none" },
];

const frostDragonDrops = [
    { name: "Frost Dragon's Fang", slot: "Amulet", attack: 7, defense: 4, rarity: "legendary", weight: 1, value: 1100, class: "Warrior" },
    { name: "Icicle Spear", slot: "Weapon", attack: 26, rarity: "legendary", weight: 50, value: 1100, class: "Warrior" },
    { name: "Frostscale Leggings", slot: "Pants", defense: 12, attack: 0, rarity: "legendary", weight: 12, value: 1100, class: "none" },
    { name: "Frost Dragon's Claw", slot: "Gloves", attack: 6, defense: 5, rarity: "legendary", weight: 3, value: 1100, class: "Warrior" },
    { name: "Frost Dragon's Heart", slot: "Accessory", attack: 4, defense: 7, rarity: "legendary", weight: 1, value: 1100, class: "Knight" },
    { name: "Frost Dragon's Scalemail", slot: "Armor", attack: 3, defense: 14, rarity: "legendary", weight: 18, value: 1100, class: "Warrior" },
    { name: "Frost Dragon's Greaves", slot: "Boots", attack: 3, defense: 7, rarity: "legendary", weight: 6, value: 1100, class: "Rogue" },
];

const stormDragonDrops = [
    { name: "Storm Dragon's Eye", slot: "Amulet", attack: 8, defense: 3, rarity: "legendary", weight: 1, value: 1200, class: "Rogue" },
    { name: "Thunder Axe", slot: "Weapon", attack: 28, rarity: "legendary", weight: 60, value: 1200, class: "Warrior" },
    { name: "Stormscale Leggings", slot: "Pants", defense: 14, attack: 0, rarity: "legendary", weight: 13, value: 1200, class: "none" },
    { name: "Storm Dragon's Claw", slot: "Gloves", attack: 7, defense: 6, rarity: "legendary", weight: 3, value: 1200, class: "Warrior" },
    { name: "Storm Dragon's Heart", slot: "Accessory", attack: 5, defense: 8, rarity: "legendary", weight: 1, value: 1200, class: "Wizard" },
    { name: "Storm Dragon's Scalemail", slot: "Armor", attack: 4, defense: 16, rarity: "legendary", weight: 21, value: 1200, class: "Knight" },
    { name: "Storm Dragon's Greaves", slot: "Boots", attack: 4, defense: 8, rarity: "legendary", weight: 7, value: 1200, class: "none" },
];

const sandSerpentDrops = [
    { name: "Sand Serpent's Fang", slot: "Amulet", attack: 9, defense: 3, rarity: "legendary", weight: 1, value: 1300, class: "Rogue" },
    { name: "Desert Saber", slot: "Weapon", attack: 30, rarity: "legendary", weight: 70, value: 1300, class: "Knight" },
    { name: "Sandscale Leggings", slot: "Pants", defense: 15, attack: 0, rarity: "legendary", weight: 14, value: 1300, class: "Knight" },
    { name: "Sand Serpent's Claw", slot: "Gloves", attack: 8, defense: 7, rarity: "legendary", weight: 3, value: 1300, class: "Warrior" },
    { name: "Sand Serpent's Heart", slot: "Accessory", attack: 6, defense: 9, rarity: "legendary", weight: 1, value: 1300, class: "Wizard" },
    { name: "Sand Serpent's Scalemail", slot: "Armor", attack: 5, defense: 17, rarity: "legendary", weight: 24, value: 1300, class: "none" },
    { name: "Sand Serpent's Greaves", slot: "Boots", attack: 5, defense: 9, rarity: "legendary", weight: 8, value: 1300, class: "none" },
];

const eternalSpecterDrops = [
    { name: "Eternal Specter's Eye", slot: "Amulet", attack: 10, defense: 4, rarity: "legendary", weight: 1, value: 1400, class: "Rogue" },
    { name: "Ghost Blade", slot: "Weapon", attack: 32, rarity: "legendary", weight: 80, value: 1400, class: "Warrior" },
    { name: "Shadow Leggings", slot: "Pants", defense: 16, attack: 0, rarity: "legendary", weight: 15, value: 1400, class: "Rogue" },
    { name: "Specter's Touch", slot: "Gloves", attack: 9, defense: 8, rarity: "legendary", weight: 3, value: 1400, class: "Warrior" },
    { name: "Eternal Heart", slot: "Accessory", attack: 7, defense: 10, rarity: "legendary", weight: 1, value: 1400, class: "Wizard" },
    { name: "Specter's Cloak", slot: "Armor", attack: 6, defense: 18, rarity: "legendary", weight: 27, value: 1400, class: "Rogue" },
    { name: "Eternal Greaves", slot: "Boots", attack: 6, defense: 10, rarity: "legendary", weight: 9, value: 1400, class: "Knight" },
];

const hydraDrops = [
    { name: "Hydra's Crown", slot: "Helmet", attack: 11, defense: 5, rarity: "legendary", weight: 5, value: 1500, class: "Wizard" },
    { name: "Hydra's Bite", slot: "Weapon", attack: 35, defense: 0, rarity: "legendary", weight: 25, value: 1500, class: "Rogue" },
    { name: "Hydra's Amulet", slot: "Accessory", attack: 12, defense: 6, rarity: "legendary", weight: 1, value: 1500, class: "none" },
    { name: "Hydra's Grasp", slot: "Gloves", attack: 10, defense: 10, rarity: "legendary", weight: 4, value: 1500, class: "Knight" },
    { name: "Hydra's Scale Armor", slot: "Armor", attack: 7, defense: 20, rarity: "legendary", weight: 30, value: 1500, class: "none" },
    { name: "Hydra's Tread", slot: "Boots", attack: 8, defense: 12, rarity: "legendary", weight: 10, value: 1500, class: "Warrior" },
    { name: "Hydra's Ring", slot: "Accessory", attack: 15, defense: 3, rarity: "legendary", weight: 1, value: 1500, class: "Wizard" },
];

export const endbosses = [
    { name: "Dragonlord", location: "Dragon's Lair", health: 200, attack: 40, defense: 20, weight: 120, drop: getRandomItem(dragonlordDrops) },
    { name: "King of Light", location: "Ancient Crypt", health: 150, attack: 30, defense: 30, weight: 100, drop: getRandomItem(kingOfLightDrops) },
    { name: "Warlord Casimir", location: "Throne Room", health: 180, attack: 35, defense: 20, weight: 200, drop: getRandomItem(warlordDrops) },
    { name: "Queen of Ember", location: "Church of the High Castle", health: 80, attack: 50, defense: 10, weight: 65, drop: getRandomItem(queenOfEmberDrops) },
    { name: "Titan", location: "Titan's Fortress", health: 250, attack: 18, defense: 25, weight: 320, drop: getRandomItem(titanDrops) },
    { name: "Swift Assassin", location: "Shadow's Peak", health: 100, attack: 60, defense: 5, weight: 60, drop: getRandomItem(swiftAssassinDrops) },
    { name: "Frost Dragon", location: "Frozen Tundra", health: 240, attack: 45, defense: 25, weight: 140, drop: getRandomItem(frostDragonDrops) },
    { name: "Storm Dragon", location: "Storm Mountain", health: 230, attack: 50, defense: 30, weight: 150, drop: getRandomItem(stormDragonDrops) },
    { name: "Sand Serpent Dragon", location: "Great Desert Oasis", health: 190, attack: 55, defense: 30, weight: 160, drop: getRandomItem(sandSerpentDrops) },
    { name: "Eternal Specter Dragon", location: "Dragon Graveyard", health: 50, attack: 60, defense: 70, weight: 0, drop: getRandomItem(eternalSpecterDrops) },
    { name: "Hydra", location: "Cove of Medra", health: 500, attack: 25, defense: 40, weight: 240, drop: getRandomItem(hydraDrops) },
];

export const baseEnemies = [
    { name: "Goblin", health: 10, attack: 10, defense: 5, weight: 60, rank: true },
    { name: "Orc", health: 20, attack: 15, defense: 10, weight: 80, rank: true },
    { name: "Troll", health: 30, attack: 20, defense: 15, weight: 120, rank: true },
    { name: "Kobold", health: 8, attack: 8, defense: 4, weight: 40, rank: true },
    { name: "Skeleton", health: 12, attack: 12, defense: 6, weight: 30 },
    { name: "Dire Wolf", health: 15, attack: 15, defense: 10, weight: 90 },
    { name: "Griffin", health: 25, attack: 20, defense: 15, weight: 140 },
    { name: "Harpy", health: 18, attack: 12, defense: 10, weight: 90 },
    { name: "Centaur", health: 25, attack: 20, defense: 15, weight: 200 },
    { name: "Minotaur", health: 35, attack: 25, defense: 20, weight: 210 },
    { name: "Giant Rat", health: 6, attack: 4, defense: 3, weight: 10 },
    { name: "Giant Bat", health: 7, attack: 2, defense: 4, weight: 4 },
    { name: "Imp", health: 9, attack: 20, defense: 5, weight: 7 },
    { name: "Shadow", health: 10, attack: 10, defense: 10, weight: 0 },
    { name: "Giant Frog", health: 12, attack: 10, defense: 8, weight: 40 },
    { name: "Zombie", health: 14, attack: 14, defense: 4, weight: 80, rank: true },
    { name: "Giant Scorpion", health: 16, attack: 12, defense: 10, weight: 20 },
    { name: "Giant Centipede", health: 10, attack: 10, defense: 5, weight: 34 },
    { name: "Giant Crab", health: 15, attack: 12, defense: 12, weight: 36 },
    { name: "Giant Lizard", health: 14, attack: 12, defense: 10, weight: 16 },
    { name: "Giant Toad", health: 12, attack: 11, defense: 9, weight: 42 },
    { name: "Swarm of Insects", health: 8, attack: 4, defense: 2, weight: 4 },
    { name: "Darkmantle", health: 10, attack: 10, defense: 10, weight: 76 },
    { name: "Giant Wasp", health: 8, attack: 8, defense: 3, weight: 12 },
    { name: "Giant Ant", health: 10, attack: 10, defense: 2, weight: 14 },
    { name: "Giant Leech", health: 6, attack: 7, defense: 1, weight: 24 },
    { name: "Giant Slug", health: 10, attack: 2, defense: 10, weight: 34 },
    { name: "Giant Moth", health: 8, attack: 6, defense: 4, weight: 18 },
    { name: "Cockatrice", health: 10, attack: 10, defense: 6, weight: 40 },
    { name: "Forrest Dragon", health: 100, attack: 30, defense: 30, weight: 420 },
    { name: "Nomad Dragon", health: 80, attack: 26, defense: 20, weight: 320 },
    { name: "Mountain Dragon", health: 84, attack: 24, defense: 28, weight: 340 },
    { name: "Mammoth Dragon", health: 100, attack: 34, defense: 20, weight: 520 },
    { name: "Chimera", health: 28, attack: 18, defense: 13, weight: 140 },
    { name: "Giant Spider", health: 22, attack: 14, defense: 12, weight: 50 },
    { name: "Gargoyle", health: 18, attack: 14, defense: 14, weight: 690 },
    { name: "Cyclops", health: 25, attack: 15, defense: 12, weight: 180 },
    { name: "Banshee", health: 15, attack: 12, defense: 12, weight: 54 },
    { name: "Manticore", health: 24, attack: 16, defense: 13, weight: 240 },
    { name: "Wyvern", health: 22, attack: 18, defense: 10, weight: 220 },
    { name: "Basilisk", health: 20, attack: 12, defense: 16, weight: 350 },
    { name: "Medusa", health: 18, attack: 14, defense: 14, weight: 120 },
    { name: "Doppelganger", health: 16, attack: 14, defense: 10, weight: 80 },
    { name: "Corrupted Unicorn", health: 20, attack: 12, defense: 12, weight: 180 },
    { name: "Naga", health: 22, attack: 15, defense: 10, weight: 160 },
    { name: "Stone Golem", health: 28, attack: 16, defense: 18, weight: 300 },
    { name: "Iron Golem", health: 30, attack: 18, defense: 20, weight: 350 },
    { name: "Clay Golem", health: 24, attack: 14, defense: 16, weight: 340 },
    { name: "Djinn", health: 18, attack: 16, defense: 10, weight: 0 },
    { name: "Female Mordur Griffin", health: 22, attack: 20, defense: 17, weight: 160 },
    { name: "Male Mordur Griffin", health: 25, attack: 18, defense: 15, weight: 180 },
    { name: "Cute Goblin", health: 5, attack: 1, defense: 0, weight: 2 },
];

export const enemiesModificators = [
    { verb: "Weak", modificator: 0.5, chance: 0.8 },
    { verb: "Strong", modificator: 2, chance: 0.2 },
    { verb: "Fast", modificator: 1.5, chance: 0.3 },
    { verb: "Slow", modificator: 0.7, chance: 0.6 },
    { verb: "Tiny", modificator: 0.6, chance: 0.4 },
    { verb: "Enormous", modificator: 2.5, chance: 0.1 },
    { verb: "Agile", modificator: 1.2, chance: 0.3 },
    { verb: "Clumsy", modificator: 0.8, chance: 0.6 },
    { verb: "Armored", modificator: 1.5, chance: 0.2 },
    { verb: "Fragile", modificator: 0.5, chance: 0.4 },
    { verb: "Intelligent", modificator: 1.3, chance: 0.3 },
    { verb: "Foolish", modificator: 0.7, chance: 0.5 },
    { verb: "Poisonous", modificator: 1.4, chance: 0.2 },
    { verb: "Resilient", modificator: 1.6, chance: 0.2 },
    { verb: "Raging", modificator: 2, chance: 0.1 },
    { verb: "Fierce", modificator: 1.7, chance: 0.2 },
    { verb: "Stealthy", modificator: 1.2, chance: 0.3 },
    { verb: "Ferocious", modificator: 1.8, chance: 0.1 },
    { verb: "Vicious", modificator: 1.6, chance: 0.2 },
    { verb: "Evasive", modificator: 1.1, chance: 0.4 },
    { verb: "Reckless", modificator: 1.5, chance: 0.3 },
    { verb: "Tenacious", modificator: 1.4, chance: 0.2 },
    { verb: "Cunning", modificator: 1.3, chance: 0.3 },
    { verb: "Infernal", modificator: 2, chance: 0.05 },
    { verb: "Divine", modificator: 1.9, chance: 0.05 },
];

export const enemiesRank = [
    { rank: "Warrior", modificator: 1.2, chance: 0.4 },
    { rank: "King", modificator: 2, chance: 0.2 },
    { rank: "Champion", modificator: 1.5, chance: 0.2 },
    { rank: "Assassin", modificator: 1.3, chance: 0.3 },
    { rank: "Berserker", modificator: 1.4, chance: 0.3 },
    { rank: "Overlord", modificator: 1.8, chance: 0.2 },
    { rank: "Guardian", modificator: 1.5, chance: 0.3 },
    { rank: "Elite", modificator: 1.7, chance: 0.24 },
    { rank: "Ancient", modificator: 2.2, chance: 0.1 },
    { rank: "Ravager", modificator: 1.3, chance: 0.4 },
    { rank: "Slayer", modificator: 1.5, chance: 0.3 },
    { rank: "Warden", modificator: 1.3, chance: 0.32 },
    { rank: "Elder", modificator: 1.9, chance: 0.16 },
    { rank: "Reaper", modificator: 1.7, chance: 0.24 },
    { rank: "Juggernaut", modificator: 2.1, chance: 0.12 },
];

export const companions = [
    { name: "Mule", description: "This is a sturdy and reliable mule, grey in color, with patient eyes and a calm demeanor. It seems to enjoy your company and does not shy away from carrying your gear.", slot: "Companion", attack: 0, defense: 0, rarity: "common", weight: -100, value: 200, class: "none" },
    { name: "Mercenary", description: `"I will fight for you. For the right sum." This Mercenary is built like a fortress; muscles layered over a broad frame. His face tells a story of numerous battles and his steel-grey eyes seem to promise more to come. He speaks with the confidence of a seasoned warrior.`, slot: "Companion", attack: 14, defense: 5, rarity: "common", weight: 100, value: 1400, class: "Warrior" },
    { name: "Elven Scout", description: `"The forest is my home, and I can guide you through it." A nimble elf with sharp eyes and a sharper bow. She moves like a shadow among the trees.`, slot: "Companion", attack: 12, defense: 3, rarity: "uncommon", weight: 60, value: 1600, class: "Archer" },
    { name: "Mysterious Mage", description: `"Magic is not just a tool. It's a way of life." A robed figure with a staff, his eyes sparkle with arcane energy. He speaks in riddles and seems to know more than he lets on.`, slot: "Companion", attack: 20, defense: 2, rarity: "rare", weight: 70, value: 2200, class: "Wizard" },
    { name: "Sneaky Cutpurse", description: `"Your purse or your life. Or in this case, I'll save your life." A rogue with a quick smile and quicker fingers. He's good in a fight, but keep an eye on your valuables.`, slot: "Companion", attack: 5, defense: 6, rarity: "uncommon", weight: 64, value: 1800, class: "Rogue" },
    { name: "Gallant Knight", description: `"For honor and glory!" A knight in shining armor, always ready to charge into battle. He's as brave as they come, and his loyalty is unswerving.`, slot: "Companion", attack: 18, defense: 8, rarity: "rare", weight: 80, value: 2400, class: "Knight" },
    { name: "Wise Hermit", description: `"The world is full of secrets. Let me share a few with you." An old man with a long beard and a staff. He may not look like much, but his knowledge is invaluable.`, slot: "Companion", attack: 2, defense: 10, rarity: "common", weight: 70, value: 1200, class: "none" },
    { name: "Dwarven Blacksmith", description: `"Need your gear fixed? I'm your dwarf." A stout dwarf with a hammer and anvil. His red hair shines like fire.`, slot: "Companion", attack: 10, defense: 6, rarity: "uncommon", weight: 100, value: 2000, class: "none" },
    { name: "Enchanting Bard", description: `"A song to lift your spirits?" A bard with a lute and a voice that can charm dragons. Her music can heal your heart and her words let tales become reality.`, slot: "Companion", attack: 1, defense: 7, rarity: "uncommon", weight: 60, value: 1700, class: "none" },
    { name: "Druid of the Claw", description: `"Nature is on our side." A druid who can shapeshift into a bear for combat. He has a deep connection with nature and can use it to aid your journey.`, slot: "Companion", attack: 16, defense: 6, rarity: "rare", weight: 77, value: 2300, class: "none" },
    { name: "Celestial Acolyte", description: `"The stars guide us." A young acolyte with a deep understanding of the celestial bodies. She can provide guidance and divine assistance.`, slot: "Companion", attack: 9, defense: 4, rarity: "uncommon", weight: 75, value: 1900, class: "none" },
    { name: "Veteran Vanguard", description: `"Stand behind me, I'll take the lead." A seasoned warrior with a large shield and spear. He's an excellent defender and can take a lot of hits.`, slot: "Companion", attack: 14, defense: 10, rarity: "rare", weight: 85, value: 2500, class: "Warrior" },
    { name: "Shadowy Assassin", description: `"You won't even see me coming." An assassin who specializes in stealth and quick kills. She's a deadly companion to have on your side.`, slot: "Companion", attack: 20, defense: 3, rarity: "rare", weight: 65, value: 3200, class: "Rogue" },
    { name: "Arcane Archer", description: `"My arrows always find their mark." An archer who infuses her arrows with magic for devastating effects. She's a valuable asset in any fight.`, slot: "Companion", attack: 18, defense: 5, rarity: "rare", weight: 74, value: 2800, class: "Archer" },
    { name: "Mystic Monk", description: `"Peace is the way, but I can fight when necessary." A monk who uses his spiritual energy to heal and protect. He's a beacon of calm in the chaos of battle.`, slot: "Companion", attack: 12, defense: 7, rarity: "uncommon", weight: 68, value: 2100, class: "none" },
    { name: "Ethereal Enchantress", description: `"Magic is everywhere, if you know where to look." An enchantress who can manipulate the magical energies around her. She can turn the tide of any battle.`, slot: "Companion", attack: 22, defense: 4, rarity: "rare", weight: 54, value: 2700, class: "Wizard" },
    { name: "Lunalia of Ewunia", description: `"Green thumb? I am bringing my green fist!" A bold wizardess that uses ancient flower magic to overcome her foes and defend her friends. A valuable and trusty companion.`, slot: "Companion", attack: 14, defense: 14, rarity: "rare", weight: 50, value: 2400, class: "Wizard" },
    { name: "Noble Paladin", description: `"In the name of justice!" A paladin who fights for righteousness. His faith is his shield, and his sword is his conviction.`, slot: "Companion", attack: 17, defense: 9, rarity: "rare", weight: 84, value: 2500, class: "Knight" },
    { name: "Beastmaster", description: `"The beasts are my friends. They can be yours too." A rugged outdoorsman that will bring his animals to fight on your side.`, slot: "Companion", attack: 14, defense: 6, rarity: "uncommon", weight: 78, value: 2200, class: "none" },
    { name: "Ghostly Guardian", description: `"In death, as in life, I serve." A spectral figure bound by honor to protect those in need. His ethereal form can withstand many attacks.`, slot: "Companion", attack: 11, defense: 15, rarity: "rare", weight: 0, value: 3000, class: "none" },
    { name: "Djinn Guide", description: `"Your wish is my command." A djinn who can provide magical assistance and valuable advice. Be careful what you wish for.`, slot: "Companion", attack: 18, defense: 8, rarity: "rare", weight: 0, value: 2800, class: "Wizard" },
    { name: "Fairy Friend", description: `"I may be small, but I can be very helpful!" A tiny fairy with defensive magic. Her light can guide you in the darkest places.`, slot: "Companion", attack: 1, defense: 8, rarity: "uncommon", weight: 1, value: 1600, class: "none" },
    { name: "Golem Guardian", description: `"I will protect you." A golem made of stone. It's slow but can take a lot of damage and deal powerful blows.`, slot: "Companion", attack: 20, defense: 20, rarity: "rare", weight: 200, value: 3200, class: "none" },
    { name: "Dragon Whelp", description: `"Rawr! Rawr?" A young dragon. It's not very big or scary yet, but it breathes fire and is looking for guidance.`, slot: "Companion", attack: 25, defense: 10, rarity: "rare", weight: 140, value: 3500, class: "none" },
    { name: "Faithful Hound", description: `"Woof!" A loyal dog that will follow you to the ends of the earth. He's doing dog stuff.`, slot: "Companion", attack: 5, defense: 3, rarity: "common", weight: 20, value: 500, class: "none" },
    { name: "Curious Cat", description: `"Meow?" A curious cat that seems to have adopted you. She's not much for fighting, but she's great company nevertheless.`, slot: "Companion", attack: 1, defense: 2, rarity: "common", weight: 4, value: 300, class: "none" },
    { name: "Majestic Eagle", description: `"Caw!" A majestic eagle with sharp eyes. It will fearlessly attack your enemies.`, slot: "Companion", attack: 8, defense: 1, rarity: "uncommon", weight: 3, value: 1200, class: "Archer" },
    { name: "Sneaky Ferret", description: `"Chitter!" A sneaky ferret that's great at getting into small spaces. It has sharp teeth.`, slot: "Companion", attack: 3, defense: 1, rarity: "common", weight: 3, value: 300, class: "none" },
    { name: "Brave Badger", description: `"Grrr!" A brave badger that's not afraid to take on enemies much larger than itself. It's a fierce fighter when cornered.`, slot: "Companion", attack: 7, defense: 2, rarity: "uncommon", weight: 5, value: 1100, class: "none" },
    { name: "Wise Owl", description: `"Hoot!" A wise owl that seems to understand more than it should. It can provide valuable advice and insight.`, slot: "Companion", attack: 3, defense: 5, rarity: "uncommon", weight: 3, value: 1000, class: "none" },
    { name: "Loyal Horse", description: `"Neigh!" A loyal horse that can carry you swiftly across the land. It's not much for fighting, but it's a great help for carrying equipment.`, slot: "Companion", attack: 2, defense: 6, rarity: "common", weight: -70, value: 1800, class: "none" },
    { name: "Gentle Giant", description: `"..." A giant who's surprisingly gentle. He's not much for conversation, but he can carry heavy loads and move large obstacles.`, slot: "Companion", attack: 15, defense: 15, rarity: "rare", weight: -120, value: 3800, class: "none" },
    { name: "Mischievous Monkey", description: `"Ooo-oo-aa-aa!" A mischievous monkey that's great at climbing and getting into places you can't. It's always up to some mischief, but it can be surprisingly helpful.`, slot: "Companion", attack: 4, defense: 3, rarity: "common", weight: -10, value: 700, class: "none" },
    { name: "Mystical Unicorn", description: `"Neigh!" A mystical unicorn with a shimmering mane. It's said to have healing powers and can purify water with its horn.`, slot: "Companion", attack: 10, defense: 10, rarity: "rare", weight: -60, value: 4500, class: "none" },
    { name: "Friendly Fox", description: `"Yip!" A friendly fox with a keen sense of smell. It can help you track creatures and will bite your enemies if neccessary.`, slot: "Companion", attack: 2, defense: 1, rarity: "uncommon", weight: 5, value: 1200, class: "none" },
    { name: "Mighty Moose", description: `"Mrrr!" A mighty moose that can carry heavy loads. It's not very fast, but it's strong and can help you traverse difficult terrain.`, slot: "Companion", attack: 2, defense: 4, rarity: "common", weight: -100, value: 2900, class: "none" },
    { name: "Benevolent Bear", description: `"Roar!" A benevolent bear with a big heart. It's a powerful ally in a fight and can keep you warm, if you dare to hug him.`, slot: "Companion", attack: 12, defense: 12, rarity: "rare", weight: -50, value: 2800, class: "none" },
    { name: "Wandering Wolf", description: `"Howl!" A wandering wolf with a keen sense of direction. It can help you navigate and hunt in the wild.`, slot: "Companion", attack: 9, defense: 4, rarity: "uncommon", weight: 7, value: 1700, class: "none" },
    { name: "Eager Beaver", description: `"Gnaw!" An eager beaver that's great at building and repairing. It can help you construct shelters and dams, if needed.`, slot: "Companion", attack: 3, defense: 3, rarity: "common", weight: 5, value: 600, class: "none" },
    { name: "Trusty Turtle", description: `"...!" A trusty turtle that's great at defense. It can shield you from attacks and it's surprisingly playful and cuddly.`, slot: "Companion", attack: 1, defense: 12, rarity: "uncommon", weight: 10, value: 1500, class: "none" },
    { name: "Vigilant Vulture", description: `"Caw!" A vigilant vulture that's great at spotting carrion. It will support you in battle, but will probably eat whoever lost afterwards.`, slot: "Companion", attack: 5, defense: 4, rarity: "common", weight: 3, value: 800, class: "none" },
    { name: "Youthful Yak", description: `"Moo!" A youthful yak that's great at carrying heavy loads. It can help you transport items and traverse difficult terrain.`, slot: "Companion", attack: 2, defense: 6, rarity: "common", weight: -80, value: 900, class: "none" },
    { name: "Bumbling Bee", description: `"Buzz!" A bumbling bee that's great at finding flowers. It will follow you. Don't step on it!`, slot: "Companion", attack: 1, defense: 0, rarity: "common", weight: 0, value: 100, class: "none" },
    { name: "Charming Chameleon", description: `"..." A charming chameleon that's great at camouflage. It can help you hide and avoid danger in battle.`, slot: "Companion", attack: 1, defense: 4, rarity: "common", weight: 0, value: 500, class: "none" },
    { name: "Energetic Emu", description: `"Caw!" An energetic emu that's great at running. It can even help you by carrying some equimpent.`, slot: "Companion", attack: 4, defense: 2, rarity: "common", weight: -30, value: 1200, class: "none" },
    { name: "Friendly Frog", description: `"Ribbit!" A friendly frog that's great at swimming. It is nice to have a frog on your side.`, slot: "Companion", attack: 1, defense: 2, rarity: "common", weight: 1, value: 600, class: "none" },
    { name: "Wandering Minstrel", description: `"A song for your troubles?" A minstrel who can lift your spirits with a song. His music can inspire you and boost your morale.`, slot: "Companion", attack: 4, defense: 3, rarity: "common", weight: 65, value: 800, class: "none" },
    { name: "Mysterious Stranger", description: `"I have many secrets to share." A stranger with a mysterious past. He's skilled in many areas and may provide unexpected help.`, slot: "Companion", attack: 10, defense: 6, rarity: "rare", weight: 70, value: 2500, class: "Rogue" },
    { name: "Experienced Hunter", description: `"The wilderness is my home." A hunter who knows how to survive in the wild. She can help you in battle.`, slot: "Companion", attack: 12, defense: 7, rarity: "uncommon", weight: 80, value: 2000, class: "none" },
    { name: "Charming Bard", description: `"Let me spin you a tale." A bard with a silver tongue. He can charm others and get you out of tricky situations.`, slot: "Companion", attack: 5, defense: 4, rarity: "uncommon", weight: 67, value: 1600, class: "none" },
    { name: "Reliable Squire", description: `"I'm ready to serve!" A squire eager to prove his worth. He can carry your equipment and assist in combat.`, slot: "Companion", attack: 8, defense: 6, rarity: "common", weight: 78, value: 1200, class: "Knight" },
    { name: "Skilled Blacksmith", description: `"Your gear is in good hands." A rugged blacksmith who can help you on your journey.`, slot: "Companion", attack: 3, defense: 8, rarity: "uncommon", weight: 85, value: 2200, class: "Knight" },
    { name: "Wise Sage", description: `"Knowledge is the greatest weapon." A sage with vast knowledge. He can provide valuable advice and insights.`, slot: "Companion", attack: 6, defense: 4, rarity: "rare", weight: 78, value: 2600, class: "Wizard" },
    { name: "Fearless Explorer", description: `"No path is too treacherous." An explorer who's not afraid of the unknown. She can help you navigate through uncharted territories.`, slot: "Companion", attack: 5, defense: 9, rarity: "uncommon", weight: 60, value: 2100, class: "Warrior" },
    { name: "Agile Acrobat", description: `"Watch this!" An acrobat with incredible agility. She can help you traverse difficult terrains and provide support in battle.`, slot: "Companion", attack: 8, defense: 6, rarity: "uncommon", weight: 60, value: 1900, class: "Rogue" },
    { name: "Stoic Guardian", description: `"I will protect you." A guardian who's dedicated to protecting others. He's a formidable defender in any fight.`, slot: "Companion", attack: 10, defense: 14, rarity: "rare", weight: 77, value: 3000, class: "Knight" },
    { name: "Enigmatic Thief", description: `"I've got quick hands." A thief with a knack for getting in and out unnoticed. She can help you steal items and sneak into places.`, slot: "Companion", attack: 10, defense: 5, rarity: "uncommon", weight: 55, value: 2200, class: "Rogue" },
    { name: "Daring Duelist", description: `"En garde!" A duelist with a flair for the dramatic. He's a skilled fighter and can help you in combat.`, slot: "Companion", attack: 15, defense: 9, rarity: "rare", weight: 68, value: 2900, class: "Warrior" },
    { name: "Humble Farmer", description: `"The soil tells a story." A farmer with a deep understanding of the land. She will stand her ground in combat.`, slot: "Companion", attack: 3, defense: 5, rarity: "common", weight: 64, value: 1000, class: "none" },
    { name: "Intrepid Archaeologist", description: `"There's history in every corner." An archaeologist with a keen eye for detail. He has fought in many crypts and ancient temples.`, slot: "Companion", attack: 7, defense: 6, rarity: "uncommon", weight: 82, value: 2300, class: "Wizard" },
]

export const sampleItems = [
    // Warrior items
    { name: "Battleaxe", slot: "Weapon", attack: 12, rarity: "common", weight: 8, value: 100, class: "Warrior" },
    { name: "Golden Battleaxe of Mordur", slot: "Weapon", attack: 1, rarity: "legendary", weight: 30, value: 2000, class: "Warrior" },
    { name: "Chainmail", slot: "Armor", defense: 7, rarity: "common", weight: 20, value: 200, class: "Warrior" },
    { name: "Mace", slot: "Weapon", attack: 10, rarity: "uncommon", weight: 10, value: 120, class: "Warrior" },
    { name: "Plate Armor", slot: "Armor", defense: 10, rarity: "rare", weight: 22, value: 300, class: "Warrior" },
    { name: "Warhammer", slot: "Weapon", attack: 15, rarity: "rare", weight: 15, value: 140, class: "Warrior" },
    { name: "Spear", slot: "Weapon", attack: 8, rarity: "common", weight: 6, value: 74, class: "Warrior" },
    { name: "Heavy Leather Boots", slot: "Boots", defense: 2, rarity: "common", weight: 4, value: 50, class: "Warrior" },
    { name: "Greatsword", slot: "Weapon", attack: 18, rarity: "rare", weight: 25, value: 260, class: "Warrior" },
    { name: "Heavy Shield", slot: "Shield", defense: 10, rarity: "uncommon", weight: 15, value: 80, class: "Warrior" },
    { name: "Plate Gauntlets", slot: "Gloves", defense: 3, rarity: "common", weight: 3, value: 7, class: "Warrior" },
    { name: "Halberd", slot: "Weapon", attack: 20, rarity: "rare", weight: 30, value: 400, class: "Warrior" },

    // Archer items
    { name: "Longbow", slot: "Weapon", attack: 10, rarity: "common", weight: 6, value: 120, class: "Archer" },
    { name: "Enchanted Longbow", slot: "Weapon", attack: 12, rarity: "uncommon", weight: 6, value: 150, class: "Archer" },
    { name: "Linen Quiver", slot: "Quiver", attack: 1, rarity: "common", weight: 3, value: 25, class: "Archer" },
    { name: "Leather Quiver", slot: "Quiver", attack: 2, rarity: "common", weight: 4, value: 80, class: "Archer" },
    { name: "Golden Quiver of Mordur", slot: "Quiver", attack: 2, defense: 1, rarity: "legendary", weight: 5, value: 1000, class: "Archer" },
    { name: "Shortbow", slot: "Weapon", attack: 8, rarity: "uncommon", weight: 4, value: 80, class: "Archer" },
    { name: "Recurve Bow", slot: "Weapon", attack: 12, rarity: "rare", weight: 8, value: 140, class: "Archer" },
    { name: "Composite Bow", slot: "Weapon", attack: 15, rarity: "rare", weight: 7, value: 170, class: "Archer" },
    { name: "Elven Armor", slot: "Armor", defense: 10, rarity: "rare", weight: 8, value: 240, class: "Archer" },
    { name: "Light Leather Boots", slot: "Boots", defense: 2, rarity: "common", weight: 2, value: 25, class: "Archer" },
    { name: "Elven Leather Boots", slot: "Boots", defense: 2, rarity: "common", weight: 1, value: 75, class: "Archer" },
    { name: "Feathered Cap", slot: "Helmet", defense: 1, rarity: "common", weight: 1, value: 35, class: "Archer" },
    { name: "Throwing Knives", slot: "Weapon", attack: 6, rarity: "common", weight: 2, value: 45, class: "Archer" },
    { name: "Hunting Spear", slot: "Weapon", attack: 12, rarity: "uncommon", weight: 5, value: 80, class: "Archer" },
    { name: "Elven Cloak", slot: "Cloak", defense: 3, rarity: "uncommon", weight: 3, value: 50, class: "Archer" },

    // Wizard items
    { name: "Wand", slot: "Weapon", attack: 6, rarity: "common", weight: 2, value: 20, class: "Wizard" },
    { name: "Golden Wand of Mordur", slot: "Weapon", attack: 14, rarity: "legendary", weight: 2, value: 1500, class: "Wizard" },
    { name: "Robes", slot: "Armor", defense: 4, rarity: "common", weight: 4, value: 50, class: "Wizard" },
    { name: "Staff", slot: "Weapon", attack: 8, rarity: "uncommon", weight: 4, value: 60, class: "Wizard" },
    { name: "Mage Armor", slot: "Armor", defense: 6, rarity: "rare", weight: 6, value: 100, class: "Wizard" },
    { name: "Crystal Orb", slot: "Weapon", attack: 12, rarity: "rare", weight: 3, value: 180, class: "Wizard" },
    { name: "Enchanted Robes", slot: "Armor", defense: 8, rarity: "rare", weight: 5, value: 200, class: "Wizard" },
    { name: "Staff of Fire", slot: "Weapon", attack: 10, rarity: "uncommon", weight: 3, value: 120, class: "Wizard" },
    { name: "Staff of Ice", slot: "Weapon", attack: 9, defense: 1, rarity: "uncommon", weight: 4, value: 120, class: "Wizard" },
    { name: "Staff of Lightning", slot: "Weapon", attack: 11, rarity: "uncommon", weight: 2, value: 120, class: "Wizard" },
    { name: "Staff of Water", slot: "Weapon", attack: 7, defense: 3, rarity: "uncommon", weight: 3, value: 120, class: "Wizard" },
    { name: "Wizard's Hat", slot: "Helmet", defense: 2, rarity: "common", weight: 1, value: 25, class: "Wizard" },
    { name: "Winding Wizard's Hat", slot: "Helmet", defense: 10, rarity: "legendary", weight: 1, value: 2500, class: "Wizard" },
    { name: "Amulet of Mana", slot: "Amulet", attack: 1, rarity: "legendary", weight: 2, value: 100, class: "Wizard" },
    { name: "Poison Cloud Weapon", slot: "Weapon", attack: 15, rarity: "rare", weight: 1, value: 400, class: "Wizard" },
    { name: "Mage's Boots", slot: "Boots", defense: 2, rarity: "uncommon", weight: 2, value: 40, class: "Wizard" },
    { name: "Shadow Wand", slot: "Weapon", attack: 20, rarity: "rare", weight: 1, value: 500, class: "Wizard" },

    // Rogue items
    { name: "Dagger", slot: "Weapon", attack: 6, rarity: "common", weight: 2, value: 35, class: "Rogue" },
    { name: "Golden Dagger of Mordur", slot: "Weapon", attack: 16, rarity: "legendary", weight: 1, value: 535, class: "Rogue" },
    { name: "Dark Leather Armor", slot: "Armor", defense: 3, rarity: "common", weight: 3, value: 60, class: "Rogue" },
    { name: "Short Sword", slot: "Weapon", attack: 8, rarity: "uncommon", weight: 4, value: 65, class: "Rogue" },
    { name: "Assassin's Blade", slot: "Weapon", attack: 12, rarity: "rare", weight: 4, value: 100, class: "Rogue" },
    { name: "Dark Leather Boots", slot: "Boots", defense: 2, rarity: "common", weight: 2, value: 35, class: "Rogue" },
    { name: "Thief Hood", slot: "Helmet", defense: 1, rarity: "common", weight: 0.5, value: 10, class: "Rogue" },
    { name: "Crossbow", slot: "Weapon", attack: 10, rarity: "uncommon", weight: 6, value: 85, class: "Rogue" },
    { name: "Throwing Daggers", slot: "Weapon", attack: 8, rarity: "uncommon", weight: 1, value: 50, class: "Rogue" },
    { name: "Poisoned Dagger", slot: "Weapon", attack: 15, rarity: "rare", weight: 2, value: 140, class: "Rogue" },
    { name: "Ninja Boots", slot: "Boots", defense: 3, rarity: "rare", weight: 1, value: 120, class: "Rogue" },
    { name: "Shadow Cloak", slot: "Cloak", defense: 5, rarity: "rare", weight: 3, value: 200, class: "Rogue" },
    { name: "Hand Crossbow", slot: "Weapon", attack: 6, rarity: "uncommon", weight: 1, value: 100, class: "Rogue" },
    { name: "Twin Daggers", slot: "Weapon", attack: 8, rarity: "rare", weight: 1, value: 80, class: "Rogue" },
    { name: "Thief's Leggings", slot: "Pants", defense: 3, attack: 0, rarity: "uncommon", weight: 5, value: 40, class: "Rogue" },

    // Knight items
    { name: "Sword", slot: "Weapon", attack: 10, rarity: "common", weight: 5, value: 100, class: "Knight" },
    { name: "Golden Longsword of Mordur", slot: "Weapon", attack: 17, defense: 2, rarity: "legendary", weight: 7, value: 1500, class: "Knight" },
    { name: "Chainmail", slot: "Armor", defense: 5, rarity: "common", weight: 10, value: 60, class: "Knight" },
    { name: "Longsword", slot: "Weapon", attack: 12, rarity: "uncommon", weight: 8, value: 130, class: "Knight" },
    { name: "Heavy Plate Armor", slot: "Armor", defense: 15, rarity: "rare", weight: 20, value: 200, class: "Knight" },
    { name: "Hammer", slot: "Weapon", attack: 8, rarity: "rare", weight: 10, value: 40, class: "Knight" },
    { name: "Enchanted Armor", slot: "Armor", defense: 12, rarity: "rare", weight: 20, value: 180, class: "Knight" },
    { name: "Shield", slot: "Shield", defense: 8, rarity: "common", weight: 10, value: 100, class: "Knight" },
    { name: "Golden Shield of Mordur", slot: "Shield", attack: -2, defense: 10, rarity: "legendary", weight: 10, value: 1500, class: "Knight" },
    { name: "Plate Boots", slot: "Boots", defense: 4, rarity: "uncommon", weight: 8, value: 80, class: "Knight" },
    { name: "Morning Star", slot: "Weapon", attack: 18, rarity: "rare", weight: 20, value: 140, class: "Knight" },
    { name: "Heavy Gauntlets", slot: "Gloves", defense: 2, rarity: "common", weight: 3, value: 70, class: "Knight" },
    { name: "Lance", slot: "Weapon", attack: 20, rarity: "rare", weight: 30, value: 280, class: "Knight" },
    { name: "Crusader's Shield", slot: "Shield", defense: 8, rarity: "rare", weight: 15, value: 180, class: "Knight" },
    { name: "Plate Helmet", slot: "Helmet", defense: 5, rarity: "uncommon", weight: 5, value: 140, class: "Knight" },
    { name: "Engraved Sword", slot: "Weapon", attack: 25, rarity: "rare", weight: 25, value: 500, class: "Knight" },
    { name: "Chain Gloves", slot: "Gloves", defense: 3, rarity: "common", weight: 2, value: 85, class: "Knight" },
    { name: "Flail", slot: "Weapon", attack: 22, rarity: "rare", weight: 25, value: 350, class: "Knight" },

    // none items
    { name: "Dwarven Armor", slot: "Armor", defense: 20, attack: 0, rarity: "uncommon", weight: 25, value: 550, class: "none" },
    { name: "Dwarven Helmet", slot: "Helmet", defense: 12, attack: 0, rarity: "uncommon", weight: 20, value: 450, class: "none" },
    { name: "Chain Shirt", slot: "Armor", defense: 4, rarity: "common", weight: 10, value: 75, class: "none" },
    { name: "Tunic", slot: "Armor", defense: 2, rarity: "common", weight: 2, value: 25, class: "none" },
    { name: "Chain Leggings", slot: "Pants", defense: 3, rarity: "common", weight: 6, value: 45, class: "none" },
    { name: "Cloth Pants", slot: "Pants", defense: 1, rarity: "common", weight: 1, value: 2, class: "none" },
    { name: "Leather Gloves", slot: "Gloves", defense: 1, rarity: "common", weight: 1, value: 20, class: "none" },
    { name: "Woolen Scarf", slot: "Accessory", defense: 1, rarity: "common", weight: 1, value: 4, class: "none" },
    { name: "Linen Cloak", slot: "Cloak", defense: 2, rarity: "common", weight: 2, value: 15, class: "none" },
    { name: "Potion of Minor Healing", slot: "Consumable", rarity: "common", weight: 1, value: 20, class: "none" },
    { name: "Potion of Greater Healing", slot: "Consumable", rarity: "uncommon", weight: 1, value: 30, class: "none" },
    { name: "Potion of Restoration", slot: "Consumable", rarity: "rare", weight: 1, value: 50, class: "none" },
    { name: "Bandage", slot: "Consumable", rarity: "common", weight: 1, value: 15, class: "none" },
    { name: "Salve", slot: "Consumable", rarity: "uncommon", weight: 1, value: 25, class: "none" },
    { name: "Antitoxin", slot: "Consumable", rarity: "rare", weight: 1, value: 40, class: "none" },
    { name: "Sling", slot: "Weapon", attack: 4, rarity: "common", weight: 1, value: 15, class: "none" },
    { name: "Quarterstaff", slot: "Weapon", attack: 6, rarity: "common", weight: 3, value: 35, class: "none" },
    { name: "Damaged Dagger", slot: "Weapon", attack: 4, rarity: "common", weight: 1, value: 15, class: "none" },
    { name: "Shortsword", slot: "Weapon", attack: 6, rarity: "common", weight: 2, value: 25, class: "none" },
    { name: "Whip", slot: "Weapon", attack: 4, rarity: "uncommon", weight: 1, value: 35, class: "none" },
    { name: "Chakram", slot: "Weapon", attack: 8, defense: -2, rarity: "rare", weight: 1, value: 75, class: "none" },
    { name: "Javelin", slot: "Weapon", attack: 6, rarity: "uncommon", weight: 2, value: 30, class: "none" },
    { name: "Net", slot: "Weapon", attack: 1, defense: 5, rarity: "uncommon", weight: 2, value: 10, class: "none" },
    { name: "Club", slot: "Weapon", attack: 4, rarity: "common", weight: 2, value: 20, class: "none" },
    { name: "Mace", slot: "Weapon", attack: 8, rarity: "uncommon", weight: 5, value: 80, class: "none" },
    { name: "Spear", slot: "Weapon", attack: 6, rarity: "common", weight: 2, value: 60, class: "none" },
    { name: "Throwing Axe", slot: "Weapon", attack: 6, rarity: "uncommon", weight: 2, value: 55, class: "none" },
    { name: "Heavy Crossbow", slot: "Weapon", attack: 12, rarity: "rare", weight: 10, value: 140, class: "none" },
    { name: "Throwing Knives", slot: "Weapon", attack: 4, rarity: "uncommon", weight: 1, value: 20, class: "none" },
    { name: "Bo Staff", slot: "Weapon", attack: 6, rarity: "common", weight: 3, value: 40, class: "none" },
    { name: "Shuriken", slot: "Weapon", attack: 4, rarity: "uncommon", weight: 1, value: 15, class: "none" },
    { name: "Nunchaku", slot: "Weapon", attack: 4, rarity: "uncommon", weight: 2, value: 25, class: "none" },
    { name: "Tonfa", slot: "Weapon", attack: 4, rarity: "uncommon", weight: 2, value: 25, class: "none" },

    // Accessories
    { name: "Gold Ring", slot: "Accessory", defense: 0, attack: 0, rarity: "rare", weight: 1, value: 500, class: "none" },
    { name: "Silver Ring", slot: "Accessory", defense: 0, attack: 0, rarity: "uncommon", weight: 1, value: 50, class: "none" },
    { name: "Copper Ring", slot: "Accessory", defense: 0, attack: 0, rarity: "common", weight: 1, value: 5, class: "none" },
    { name: "Lucky Charm", slot: "Accessory", defense: 1, attack: 1, rarity: "uncommon", weight: 1, value: 30, class: "none" },
    { name: "Amulet of the Moon", slot: "Accessory", defense: 2, attack: 0, rarity: "legendary", weight: 1, value: 100, class: "none" },
    { name: "Amulet of the Sun", slot: "Accessory", defense: 0, attack: 2, rarity: "legendary", weight: 1, value: 100, class: "none" },
    { name: "Silk Scarf", slot: "Accessory", defense: 1, attack: 0, rarity: "uncommon", weight: 1, value: 20, class: "none" },
    { name: "Jeweled Brooch", slot: "Accessory", defense: 1, attack: 1, rarity: "rare", weight: 1, value: 200, class: "none" },
    { name: "Leather Wristband", slot: "Accessory", defense: 1, attack: 0, rarity: "common", weight: 1, value: 5, class: "none" },
    { name: "Crystal Pendant", slot: "Accessory", defense: 2, attack: 0, rarity: "rare", weight: 1, value: 150, class: "none" },
    { name: "Obsidian Necklace", slot: "Accessory", defense: 0, attack: 1, rarity: "rare", weight: 1, value: 150, class: "none" },
    { name: "Obsidian Moon Necklace", slot: "Accessory", defense: 4, attack: 0, rarity: "rare", weight: 1, value: 150, class: "none" },
    { name: "Hemp Necklace", slot: "Accessory", defense: 1, attack: 0, rarity: "common", weight: 1, value: 2, class: "none" },
    { name: "Feathered Headband", slot: "Accessory", defense: 1, attack: 0, rarity: "uncommon", weight: 1, value: 10, class: "none" },
    { name: "Leather Headband", slot: "Accessory", defense: 1, attack: 0, rarity: "common", weight: 1, value: 5, class: "none" },
    { name: "Beaded Bracelet", slot: "Accessory", defense: 1, attack: 0, rarity: "common", weight: 1, value: 5, class: "none" },
    { name: "Jade Earrings", slot: "Accessory", defense: 1, attack: 0, weight: 1, value: 20, class: "none" },
    { name: "Silver Necklace", slot: "Accessory", defense: 1, attack: 0, weight: 1, value: 30, class: "none" },
    { name: "Crystal Bracelet", slot: "Accessory", defense: 1, attack: 0, weight: 1, value: 25, class: "none" },
    { name: "Gold Earrings", slot: "Accessory", defense: 1, attack: 0, weight: 1, value: 100, class: "none" },
    { name: "Silver Bracelet", slot: "Accessory", defense: 1, attack: 0, weight: 1, value: 30, class: "none" },
    { name: "Diamond Ring", slot: "Accessory", defense: 1, attack: 0, weight: 1, value: 200, class: "none" },

    // Pants
    { name: "Chainmail Leggings", slot: "Pants", defense: 5, attack: 0, rarity: "uncommon", weight: 15, value: 80, class: "none" },
    { name: "Leather Breeches", slot: "Pants", defense: 3, attack: 0, rarity: "common", weight: 7, value: 30, class: "none" },
    { name: "Cotton Pants", slot: "Pants", defense: 1, attack: 0, rarity: "common", weight: 2, value: 10, class: "none" },
    { name: "Silk Trousers", slot: "Pants", defense: 1, attack: 0, rarity: "rare", weight: 1, value: 150, class: "none" },
    { name: "Plate Leggings", slot: "Pants", defense: 8, attack: 0, rarity: "rare", weight: 20, value: 200, class: "none" },
    { name: "Woolen Pants", slot: "Pants", defense: 2, attack: 0, rarity: "common", weight: 3, value: 15, class: "none" },
    { name: "Studded Leather Pants", slot: "Pants", defense: 4, attack: 0, rarity: "uncommon", weight: 10, value: 50, class: "none" },
    { name: "Ringmail Leggings", slot: "Pants", defense: 6, attack: 0, rarity: "uncommon", weight: 13, value: 100, class: "none" },
    { name: "Iron Legguards", slot: "Pants", defense: 7, attack: 0, rarity: "rare", weight: 18, value: 180, class: "none" },
    { name: "Bronze Legplates", slot: "Pants", defense: 6, attack: 0, rarity: "uncommon", weight: 16, value: 90, class: "none" },
    { name: "Gold Legplates of Mordur", slot: "Pants", defense: 8, attack: 0, rarity: "legendary", weight: 16, value: 690, class: "none" },
    { name: "Scaled Pants", slot: "Pants", defense: 5, attack: 0, rarity: "rare", weight: 12, value: 120, class: "none" },
    { name: "Elven Pants", slot: "Pants", defense: 4, attack: 0, rarity: "rare", weight: 5, value: 140, class: "none" },
    { name: "Dwarven Trousers", slot: "Pants", defense: 7, attack: 0, rarity: "rare", weight: 17, value: 190, class: "none" },
    { name: "Ranger's Leggings", slot: "Pants", defense: 3, attack: 0, rarity: "uncommon", weight: 6, value: 60, class: "none" },
    { name: "Sorcerer's Pants", slot: "Pants", defense: 2, attack: 0, rarity: "uncommon", weight: 4, value: 70, class: "none" },
    { name: "Knight's Greaves", slot: "Pants", defense: 9, attack: 0, rarity: "rare", weight: 19, value: 210, class: "none" },
    { name: "Assassin's Leggings", slot: "Pants", defense: 4, attack: 0, rarity: "uncommon", weight: 5, value: 75, class: "none" },
    { name: "Warlock's Pants", slot: "Pants", defense: 3, attack: 0, rarity: "uncommon", weight: 4, value: 65, class: "none" },
    { name: "Padded Pants", slot: "Pants", defense: 3, attack: 0, rarity: "common", weight: 5, value: 25, class: "none" },
    { name: "Fur Leggings", slot: "Pants", defense: 3, attack: 0, rarity: "common", weight: 6, value: 35, class: "none" },
    { name: "Linen Pants", slot: "Pants", defense: 1, attack: 0, rarity: "common", weight: 2, value: 12, class: "none" },
    { name: "Magician's Pants", slot: "Pants", defense: 2, attack: 0, rarity: "uncommon", weight: 3, value: 45, class: "none" },
    { name: "Bard's Trousers", slot: "Pants", defense: 2, attack: 0, rarity: "uncommon", weight: 3, value: 50, class: "none" },
    { name: "Druid's Leggings", slot: "Pants", defense: 3, attack: 0, rarity: "uncommon", weight: 4, value: 80, class: "none" },
    { name: "Paladin's Greaves", slot: "Pants", defense: 8, attack: 0, rarity: "rare", weight: 18, value: 220, class: "none" },
    { name: "Necromancer's Pants", slot: "Pants", defense: 3, attack: 0, rarity: "uncommon", weight: 4, value: 90, class: "none" },
    { name: "Samurai's Legplates", slot: "Pants", defense: 7, attack: 0, rarity: "rare", weight: 16, value: 170, class: "none" },

    // Socks
    { name: "Woolen Socks", slot: "Socks", defense: 1, attack: 0, rarity: "common", weight: 1, value: 5, class: "none" },
    { name: "Silk Socks", slot: "Socks", defense: 1, attack: 0, rarity: "rare", weight: 0.5, value: 25, class: "none" },
    { name: "Cotton Socks", slot: "Socks", defense: 1, attack: 0, rarity: "common", weight: 1, value: 7, class: "none" },
    { name: "Linen Socks", slot: "Socks", defense: 1, attack: 0, rarity: "common", weight: 1, value: 6, class: "none" },
    { name: "Elven Socks", slot: "Socks", defense: 1, attack: 0, rarity: "uncommon", weight: 0.5, value: 15, class: "Archer" },
    { name: "Dwarven Socks", slot: "Socks", defense: 2, attack: 0, rarity: "uncommon", weight: 1, value: 20, class: "none" },
    { name: "Ranger's Socks", slot: "Socks", defense: 1, attack: 0, rarity: "uncommon", weight: 1, value: 10, class: "Warrior" },
    { name: "Sorcerer's Socks", slot: "Socks", defense: 1, attack: 0, rarity: "uncommon", weight: 1, value: 12, class: "Wizard" },
    { name: "Knight's Socks", slot: "Socks", defense: 2, attack: 0, rarity: "uncommon", weight: 1, value: 18, class: "Knight" },
    { name: "Assassin's Socks", slot: "Socks", defense: 2, attack: 0, rarity: "uncommon", weight: 0.5, value: 31, class: "Rogue" },
    { name: "Warlock's Socks", slot: "Socks", defense: 1, attack: 0, rarity: "uncommon", weight: 1, value: 14, class: "none" },
    { name: "Priest's Socks", slot: "Socks", defense: 1, attack: 0, rarity: "uncommon", weight: 1, value: 9, class: "none" },
    { name: "Padded Socks", slot: "Socks", defense: 2, attack: 0, rarity: "uncommon", weight: 1, value: 16, class: "none" },
    { name: "Fur Socks", slot: "Socks", defense: 2, attack: 0, rarity: "uncommon", weight: 1, value: 22, class: "none" },
    { name: "Magician's Socks", slot: "Socks", defense: 1, attack: 0, rarity: "uncommon", weight: 1, value: 13, class: "Wizard" },
    { name: "Thief's Socks", slot: "Socks", defense: 1, attack: 0, rarity: "uncommon", weight: 0.5, value: 20, class: "Rogue" },

    // Gloves
    { name: "Leather Gloves", slot: "Gloves", defense: 2, attack: 0, rarity: "common", weight: 2, value: 10, class: "none" },
    { name: "Chainmail Gloves", slot: "Gloves", defense: 4, attack: 0, rarity: "uncommon", weight: 4, value: 25, class: "none" },
    { name: "Elven Gloves", slot: "Gloves", defense: 3, attack: 0, rarity: "uncommon", weight: 2, value: 30, class: "Archer" },
    { name: "Dwarven Gloves", slot: "Gloves", defense: 5, attack: 0, rarity: "uncommon", weight: 5, value: 45, class: "none" },
    { name: "Ranger's Gloves", slot: "Gloves", defense: 2, attack: 0, rarity: "uncommon", weight: 3, value: 20, class: "Warrior" },
    { name: "Sorcerer's Gloves", slot: "Gloves", defense: 2, attack: 0, rarity: "uncommon", weight: 2, value: 22, class: "Wizard" },
    { name: "Knight's Gauntlets", slot: "Gloves", defense: 6, attack: 0, rarity: "rare", weight: 7, value: 60, class: "Knight" },
    { name: "Assassin's Gloves", slot: "Gloves", defense: 3, attack: 0, rarity: "uncommon", weight: 2, value: 45, class: "Rogue" },
    { name: "Warlock's Gloves", slot: "Gloves", defense: 2, attack: 0, rarity: "uncommon", weight: 2, value: 28, class: "none" },
    { name: "Padded Gloves", slot: "Gloves", defense: 3, attack: 0, rarity: "common", weight: 3, value: 15, class: "none" },
    { name: "Fur Gloves", slot: "Gloves", defense: 3, attack: 0, rarity: "uncommon", weight: 4, value: 40, class: "none" },
    { name: "Magician's Gloves", slot: "Gloves", defense: 2, attack: 0, rarity: "uncommon", weight: 2, value: 25, class: "Wizard" },
    { name: "Thief's Gloves", slot: "Gloves", defense: 2, attack: 0, rarity: "uncommon", weight: 2, value: 20, class: "Rogue" },
    { name: "Bard's Gloves", slot: "Gloves", defense: 2, attack: 0, rarity: "uncommon", weight: 2, value: 32, class: "none" },

    // Boots
    { name: "Leather Boots", slot: "Boots", defense: 2, attack: 0, rarity: "common", weight: 3, value: 12, class: "none" },
    { name: "Chainmail Boots", slot: "Boots", defense: 4, attack: 0, rarity: "uncommon", weight: 5, value: 30, class: "none" },
    { name: "Elven Boots", slot: "Boots", defense: 3, attack: 0, rarity: "uncommon", weight: 2, value: 35, class: "Archer" },
    { name: "Dwarven Boots", slot: "Boots", defense: 5, attack: 0, rarity: "uncommon", weight: 6, value: 50, class: "none" },
    { name: "Ranger's Boots", slot: "Boots", defense: 2, attack: 0, rarity: "uncommon", weight: 3, value: 25, class: "Warrior" },
    { name: "Sorcerer's Boots", slot: "Boots", defense: 2, attack: 0, rarity: "uncommon", weight: 3, value: 27, class: "Wizard" },
    { name: "Knight's Greaves", slot: "Boots", defense: 6, attack: 0, rarity: "rare", weight: 8, value: 65, class: "Knight" },
    { name: "Assassin's Boots", slot: "Boots", defense: 3, attack: 0, rarity: "uncommon", weight: 2, value: 50, class: "Rogue" },
    { name: "Warlock's Boots", slot: "Boots", defense: 2, attack: 0, rarity: "uncommon", weight: 3, value: 33, class: "none" },
    { name: "Padded Boots", slot: "Boots", defense: 3, attack: 0, rarity: "common", weight: 4, value: 18, class: "none" },
    { name: "Fur Boots", slot: "Boots", defense: 3, attack: 0, rarity: "uncommon", weight: 5, value: 45, class: "none" },
    { name: "Magician's Boots", slot: "Boots", defense: 2, attack: 0, rarity: "uncommon", weight: 3, value: 30, class: "Wizard" },
    { name: "Thief's Boots", slot: "Boots", defense: 2, attack: 0, rarity: "uncommon", weight: 2, value: 25, class: "Rogue" },
    { name: "Bard's Boots", slot: "Boots", defense: 2, attack: 0, rarity: "uncommon", weight: 3, value: 37, class: "none" },

    // Underwear
    { name: "Cotton Underwear", slot: "Underwear", defense: 1, attack: 0, rarity: "common", weight: 1, value: 5, class: "none" },
    { name: "Silk Underwear", slot: "Underwear", defense: 1, attack: 0, rarity: "rare", weight: 0.5, value: 25, class: "none" },
    { name: "Woolen Underwear", slot: "Underwear", defense: 1, attack: 0, rarity: "common", weight: 1, value: 7, class: "none" },
    { name: "Linen Underwear", slot: "Underwear", defense: 1, attack: 0, rarity: "common", weight: 1, value: 6, class: "none" },
    { name: "Elven Underwear", slot: "Underwear", defense: 1, attack: 0, rarity: "uncommon", weight: 0.5, value: 15, class: "Archer" },
    { name: "Dwarven Underwear", slot: "Underwear", defense: 2, attack: 0, rarity: "uncommon", weight: 1, value: 20, class: "none" },
    { name: "Ranger's Underwear", slot: "Underwear", defense: 1, attack: 0, rarity: "uncommon", weight: 1, value: 10, class: "Warrior" },
    { name: "Sorcerer's Underwear", slot: "Underwear", defense: 1, attack: 0, rarity: "uncommon", weight: 1, value: 12, class: "Wizard" },
    { name: "Knight's Underwear", slot: "Underwear", defense: 2, attack: 0, rarity: "uncommon", weight: 1, value: 18, class: "Knight" },
    { name: "Assassin's Underwear", slot: "Underwear", defense: 2, attack: 0, rarity: "uncommon", weight: 0.5, value: 31, class: "Rogue" },
    { name: "Warlock's Underwear", slot: "Underwear", defense: 1, attack: 0, rarity: "uncommon", weight: 1, value: 14, class: "none" },
    { name: "Padded Underwear", slot: "Underwear", defense: 2, attack: 0, rarity: "uncommon", weight: 1, value: 16, class: "none" },
    { name: "Fur Underwear", slot: "Underwear", defense: 2, attack: 0, rarity: "uncommon", weight: 1, value: 22, class: "none" },
    { name: "Magician's Underwear", slot: "Underwear", defense: 1, attack: 0, rarity: "uncommon", weight: 1, value: 13, class: "Wizard" },
    { name: "Thief's Underwear", slot: "Underwear", defense: 1, attack: 0, rarity: "uncommon", weight: 0.5, value: 14, class: "Rogue" },
    { name: "Cotton Comfort", slot: "Underwear", defense: 1, attack: 0, rarity: "common", weight: 1, value: 5, class: "none" },
    { name: "Silk Elegance", slot: "Underwear", defense: 1, attack: 0, rarity: "rare", weight: 0.5, value: 25, class: "none" },
    { name: "Woolen Warmth", slot: "Underwear", defense: 1, attack: 0, rarity: "common", weight: 1, value: 7, class: "none" },
    { name: "Linen Lightness", slot: "Underwear", defense: 1, attack: 0, rarity: "common", weight: 1, value: 6, class: "none" },
    { name: "Elven Ease", slot: "Underwear", defense: 1, attack: 0, rarity: "uncommon", weight: 0.5, value: 15, class: "Archer" },
    { name: "Dwarven Durability", slot: "Underwear", defense: 4, attack: 0, rarity: "uncommon", weight: 1, value: 20, class: "none" },
    { name: "Ranger's Resilience", slot: "Underwear", defense: 1, attack: 0, rarity: "uncommon", weight: 1, value: 10, class: "Warrior" },
    { name: "Sorcerer's Secret", slot: "Underwear", defense: 1, attack: 0, rarity: "uncommon", weight: 1, value: 12, class: "Wizard" },
    { name: "Knight's Knickers", slot: "Underwear", defense: 2, attack: 0, rarity: "uncommon", weight: 1, value: 18, class: "Knight" },
    { name: "Assassin's Attire", slot: "Underwear", defense: 2, attack: 0, rarity: "uncommon", weight: 0.5, value: 31, class: "Rogue" },
    { name: "Padded Protection", slot: "Underwear", defense: 3, attack: 0, rarity: "uncommon", weight: 1, value: 16, class: "none" },
    { name: "Fur Finery", slot: "Underwear", defense: 2, attack: 0, rarity: "uncommon", weight: 1, value: 22, class: "none" },
    { name: "Magician's Mystery", slot: "Underwear", defense: 1, attack: 0, rarity: "uncommon", weight: 1, value: 13, class: "Wizard" },
    { name: "Thief's Thrill", slot: "Underwear", defense: 1, attack: 1, rarity: "uncommon", weight: 0.5, value: 14, class: "Rogue" },
    { name: "Bard's Breeches", slot: "Underwear", defense: 1, attack: 0, rarity: "uncommon", weight: 1, value: 15, class: "none" },
    { name: "Paladin's Pantaloons", slot: "Underwear", defense: 2, attack: 0, rarity: "uncommon", weight: 1, value: 18, class: "none" },
    { name: "Scribe's Skivvies", slot: "Underwear", defense: 1, attack: 0, rarity: "uncommon", weight: 1, value: 12, class: "none" },
    { name: "Summoner's Shorts", slot: "Underwear", defense: 1, attack: 0, rarity: "uncommon", weight: 1, value: 13, class: "none" },
    { name: "Berserker's Pantaloons", slot: "Underwear", defense: 2, attack: 1, rarity: "uncommon", weight: 1, value: 19, class: "none" },
    { name: "Enchanter's Essentials", slot: "Underwear", defense: 1, attack: 0, rarity: "uncommon", weight: 1, value: 15, class: "none" },

    // Belts
    { name: "BraidedRroot", slot: "Belt", defense: 1, attack: 1, rarity: "common", weight: 4, value: 2, class: "Wizard" },
    { name: "Knit", slot: "Belt", defense: 0, attack: 0, rarity: "common", weight: 1, value: 1, class: "none" },
    { name: "Leather Belt", slot: "Belt", defense: 1, attack: 0, rarity: "common", weight: 1, value: 10, class: "none" },
    { name: "Chain Belt", slot: "Belt", defense: 2, attack: 0, rarity: "uncommon", weight: 2, value: 20, class: "Knight" },
    { name: "Plated Belt", slot: "Belt", defense: 3, attack: 0, rarity: "rare", weight: 3, value: 50, class: "Knight" },
    { name: "Warrior's Belt", slot: "Belt", defense: 4, attack: 1, rarity: "uncommon", weight: 2, value: 100, class: "Warrior" },
    { name: "Thief's Belt", slot: "Belt", defense: 1, attack: 2, rarity: "uncommon", weight: 1, value: 100, class: "Rogue" },
    { name: "Mage's Belt", slot: "Belt", defense: 0, attack: 3, rarity: "uncommon", weight: 1, value: 100, class: "Wizard" },
    { name: "Silk Belt", slot: "Belt", defense: 1, attack: 0, rarity: "uncommon", weight: 1, value: 15, class: "Archer" },
    { name: "Braided Belt", slot: "Belt", defense: 1, attack: 0, rarity: "common", weight: 1, value: 5, class: "none" },
    { name: "Jeweled Belt", slot: "Belt", defense: 2, attack: 1, rarity: "rare", weight: 1, value: 75, class: "none" },
    { name: "Studded Leather Belt", slot: "Belt", defense: 2, attack: 0, rarity: "uncommon", weight: 2, value: 25, class: "Archer" },
    { name: "Obsidian Belt", slot: "Belt", defense: 3, attack: 0, rarity: "rare", weight: 2, value: 60, class: "none" },
    { name: "Golden Belt", slot: "Belt", defense: 1, attack: 0, rarity: "uncommon", weight: 1, value: 30, class: "none" },
    { name: "Crystal Belt", slot: "Belt", defense: 2, attack: 0, rarity: "rare", weight: 1, value: 40, class: "Wizard" },
    { name: "Adventurer's Belt", slot: "Belt", defense: 2, attack: 2, rarity: "uncommon", weight: 1, value: 120, class: "none" },
    { name: "Runic Belt", slot: "Belt", defense: 3, attack: 1, rarity: "uncommon", weight: 1, value: 150, class: "none" },
    { name: "Serpentine Belt", slot: "Belt", defense: 1, attack: 0, rarity: "uncommon", weight: 1, value: 20, class: "Wizard" },
    { name: "Viking Belt", slot: "Belt", defense: 3, attack: 2, rarity: "rare", weight: 3, value: 80, class: "Warrior" },
    { name: "Assassin's Belt", slot: "Belt", defense: 1, attack: 3, rarity: "uncommon", weight: 1, value: 100, class: "Rogue" },
]