export const patchNotesData = [
    {
        version: "2.0",
        notes: [
            "Introducing artwork for the over 80 locations and the over 40 enemy types, including endbosses, to enhance visual engagement and enjoyment",
            "Players can click on artwork to view detailed images in a popup",
            "Increased the pace of text for a more dynamic and fluid gameplay experience",
            "Added visual effects to health, providing immediate feedback on damage inflicted or received in battles",
            "Adaptive Difficulty System: New gameplay feature to maintain a level of challenge and excitement throughout each adventure",
            "Introducing The Hydra: A new endboss with a formidable health pool, offering new unique drops",
            "Addition of new enemies and locations",
            "Enhanced clarity and readability in the User Interface, including the bolding of key values",
            "Refined damage calculation for a more challenging yet fair combat experience, particularly in high-defense scenarios",
            "Introduced a \"The Numbers\" popup in the menu, displaying key game content statistics",
            "Added belts as new item type and added 20 new belt items",
        ],
    },
    {
        version: "1.6",
        notes: [
            "Unveiling Companions: Engage with any of the 60 unique allies ready to assist you in your valiant quest",
            "Empower your companion towards legendary status, at which point they not only gain enhanced strength but also no longer necessitate a gold upkeep",
            "Defeat the new end bosses and gather even more legendary loot – four new and powerful dragons await you!",
            "Implemented a probability for certain items to qualify as \"Collectibles\", making them highly valuable for trade, albeit otherwise non-functional",
            "Revised Item Generation for lesser production of \"Old\" items, fostering a broader diversity of common items",
            "Ten Cards will now only be accessible in random trading locales, but offer a larger gold pool where available",
            "Balanced the enemies to go with the additions and changes",
            "Kindly note, the aforementioned updates will come into play in your forthcoming adventure – Your ongoing quest will remain unchanged",
            "Introduced a dynamic element with the possibility for attacks to miss, making combat scenarios more thrilling",
            "Resolved a bug where the \"Start New Adventure\" button was missing post vanquishing the end boss",
            "Further improvements to UI, both in styling as well as in functionality",
            "Minor improvements in language and wording",
        ],
    },
    {
        version: "1.5",
        notes: [
            `Refined enemy rank allocation: Now, only certain enemy types can possess ranks such as "Berserker" or "Warden" – Moreover, the chance of encountering ranked enemies doubled – as a result, you'll see no more "Giant Slug Assassins" and more "Zombie Overlords"`,
            "Enhanced item generation system to provide even greater item diversity",
            "Introduced an underwear slot to the equipment system",
            "Added 36 unique underwear items, and one of these will be included in the player's starting equipment",
            "Please note that all the changes above will take effect in your next adventure – Your current adventure will remain unaffected",
            "Enhanced combat dynamics: Damage calculations are now performed not instantly upon clicking the attack button, but sequentially after each message has been fully displayed",
            "Enhanced inventory and trade list readability",
            "Improved popup responsiveness",
            "Minor wording improvements",
        ],
    },
    {
        version: "1.4",
        notes: [
            "Converted Timeless Tales into a Progressive Web App (PWA) for offline play, supporting desktops and smartphones (if your device and browser support this feature, a download button will appear in the top right corner)",
            "Eliminated visual clutter by preventing Update Notes from showing when the Storage Acknowledgement Window opened on page load",
            "Streamlined the data storage warning to display only once per page load",
            "Revised the data storage warning text",
            "Integrated a loading symbol into the splash screen",
            "Implemented additional minor enhancements",
        ],
    },
    {
        version: "1.3.5",
        notes: [
            "Introducing update note history: From now on, update notes will be archived and accessible in future updates (Note that this feature starts with the previous update, and earlier update notes are not fully available)",
            "Added favicon",
            "Added smooth fade out effect to splash screen",
        ],
    },
    {
        version: "1.3.4",
        notes: [
            "Players will now start in a village",
            "Before the end boss, the players will pass the Forge of Legends",
            "Make items legendary within the Forge of Legends (requires 1000 Gold)",
            "Now there will be a 50% chance that AI will take the first turn in Ten Cards",
            "Added scrollbars",
            "Added fullscreen button",
            "Added splash screen",
            "Added Timeless Tales Logo to Ancient Style",
            "Improvements to Ten Cards AI (medium and hard)",
            "Improved: No more duplicate logs when reloading",
            "Improved: Logs are saved directly, so they should remain properly when reloading",
            "Fixed: Negative gold values for locations when betting on Ten Cards",
            "More little fixes and improvements",
        ],
    },
    {
        version: "1.0 to 1.3.3",
        notes: [
            "Various content updates (i.e. Items, Enemies and Locations)",
            "Various feature updates, including the introduction of the minigame Ten Cards",
            "Introduction of the three styles for the game (Ancient, Retro and Modern)",
            "Balancing",
        ],
    },
];  